on: [push]

name: build

jobs:
  build:
    name: build examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          # Build for Cortex-M7F with FPU support
          targets: thumbv7em-none-eabihf
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target thumbv7em-none-eabihf
